version: "3.9"
services:
  hermes:
    build:
      context: ./iot-hermes
      dockerfile: Dockerfile
    container_name: hermes
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PROFILE=pi
      - APOLLO_SERVICE_PATH=http://apollo:8181
    depends_on:
      - apollo
      - postgres
      - influxdb
      - kafka
  apollo:
    build:
      context: ./iot-apollo
    container_name: apollo
    restart: always
    ports:
      - "8181:8181"
    volumes:
      - ./iot-apollo/logs:/apps/iot-apollo/logs
    environment:
      - PROFILE=pi
  demeter:
    build:
      context: ./iot-demeter
      dockerfile: Dockerfile
    container_name: demeter
    restart: always
    ports:
      - "8282:8282"
    environment:
      - PROFILE=pi
    depends_on:
      - postgres
  postgres:
    image: 'postgres'
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=welcome1
      - POSTGRES_DB=public_transport_db
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=user
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=public-transport
      - DOCKER_INFLUXDB_INIT_BUCKET=vehicles-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=Y3oa11jMBJKnxTuXVNWXcpFZDryOb88F4re4LFMer3cucUixrBP0pl0W27ePhMG0hsKbHgkfVjs2VhLKJmh2ew==
      - DOCKER_INFLUXDB_INIT_RETENTION=3d
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./etc/grafana/vendor/plugins:/var/lib/grafana/plugins:ro
      - ./etc/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./etc/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./etc/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - influxdb
      - postgres
      - prometheus
  prometheus:
    image: ubuntu/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./etc/prometheus/rules:/etc/prometheus/rules:ro
    depends_on:
      - hermes
      - apollo
      - demeter
      - node_exporter
  node_exporter:
    image: bitnami/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    #  promtail:
    #    image: grafana/promtail
    #    ports:
    #      - "3100:3100"
    #    depends_on:
    #      - loki
    #  logstash:
    #    image: logstash:8.0.0
    #    container_name: logstash
    #    ports:
    #      - "9200:9200"
    #    volumes:
    #      - ./:/tmp/elasticsearch
    #      - ./etc/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    #      - ./etc/logstash/conf/logstash.conf:/usr/share/logstash/conf/logstash.conf
    #      - ./etc/logstash/pipeline:/usr/share/logstash/pipeline:ro
    #    environment:
    #      - java.io.tmpdir=${ES_TMPDIR}
    #    depends_on:
    #      - loki
  #  loki:
  #    image: grafana/loki:2.4.2
  #    ports:
  #      - "3100:3100"
  #    command: -config.file=./etc/loki/config.yaml
  #    networks:
  #  elasticsearch:
  #    image: elasticsearch:8.0.0
  #    container_name: elasticsearch
  #    ports:
  #      - "9200:9200"
  #      - "9300:9300"
  #    environment:
  #      ES_JAVA_OPTS: -Xmx256m -Xms256m
  #      ELASTIC_PASSWORD: 'changeme'
  #      discovery.type: single-node
  #    volumes:
  #      - ./etc/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  #      - elasticsearch:/usr/share/elasticsearch/data:z
  #volumes:
  #  elasticsearch:

#  zookeeper:
#    image: bitnami/zookeeper:latest
#    container_name: zookeeper
#  kafka:
#    image: bitnami/kafka:latest
#    container_name: kafka
#    depends_on:
#      - zookeeper
