{
 "title": "Warsaw",
 "tags": [ "WAWA" ],
 "time": { "from": "now-12h", "to": "now-30s" },
 "refresh": "10s",
 "panels": [
  {
   "title": "General Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Vehicles Live",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (vehicle_number) vehicle_number, time, to_number(lat, '99.99999999') AS \"latitude\", to_number(lon, '99.99999999') AS \"longitude\", line AS \"name\",\r\nCASE WHEN vehicle_type = 'BUS' AND line NOT LIKE 'N%' THEN 1 WHEN vehicle_type = 'TRAM' THEN 2 WHEN vehicle_type = 'BUS' AND line LIKE 'N%' THEN 3 ELSE 0 END AS \"metric\"\r\nFROM vehicle_location WHERE city_code = 'WAWA' AND time >= now() - interval '5 minutes' AND $__timeFilter(time) ORDER BY 1, 2 DESC;"
    }
   ]
  },
  {
   "title": "Buses",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT now() as time_range, COUNT(DISTINCT vehicle_number) as metric \r\nFROM vehicle_location WHERE city_code = 'WAWA' AND vehicle_type = 'BUS' AND line NOT LIKE 'N%' AND time >= now() - interval '5 minutes' GROUP BY time_range ORDER BY time_range DESC;"
    }
   ]
  },
  {
   "title": "Trams",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT now() as time_range, COUNT(DISTINCT vehicle_number) as metric \r\nFROM vehicle_location WHERE city_code = 'WAWA' AND vehicle_type = 'TRAM' AND time >= now() - interval '5 minutes' GROUP BY time_range ORDER BY time_range DESC;"
    }
   ]
  },
  {
   "title": "Night",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT now() as time_range, COUNT(DISTINCT vehicle_number) as metric \r\nFROM vehicle_location WHERE city_code = 'WAWA' AND vehicle_type = 'BUS' AND line LIKE 'N%' AND time >= now() - interval '5 minutes' GROUP BY time_range ORDER BY time_range DESC;"
    }
   ]
  },
  {
   "title": "Departures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('day', timetable_departure_date) AS \"time\", count(*) number_of_departures\nFROM timetables\n-- WHERE $__timeFilter(timetable_departure_date)\nGROUP BY DATE_TRUNC('day', timetable_departure_date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Percentage of covered timetables",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('hour', timetable_departure_date) as \"time\",\n       100.0 * sum(CASE WHEN arrival_date IS NOT NULL then 1 else 0 END) / count(*) as \"percentage\"\nFROM timetables\nWHERE line NOT IN ('WKD', 'S1', 'S2', 'S3', 'R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'R8', 'R9') AND $__timeFilter(timetable_departure_date)\nGROUP BY date_trunc('hour', timetable_departure_date);"
    }
   ]
  },
  {
   "title": "Number of vehicles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT time_range as time, metric FROM (SELECT to_timestamp(floor((extract('epoch' from time) / 600)) * 600) as time_range, COUNT(DISTINCT vehicle_number) as metric\nFROM vehicle_location WHERE $__timeFilter(time) GROUP BY time_range ORDER BY time_range DESC) AS number_of_vehicles;"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  lat,\n  lon,\n  timetable_departure_date AS \"time\",\n  date_part('minutes', departure_date - timetable_departure_date) AS \"value\"\nFROM timetables\nWHERE\n  $__timeFilter(timetable_departure_date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Delays",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  }
 ]
}