{
 "title": "API",
 "time": { "from": "2022-02-22T12:23:43.140Z", "to": "2022-02-22T20:13:27.751Z" },
 "panels": [
  { "title": "System availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hermes",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"hermes\"}"
    }
   ]
  },
  {
   "title": "Apollo",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"apollo\"}"
    }
   ]
  },
  { "title": "Apollo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Timetable Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(iot_apollo_api_get_timetables_seconds_sum{job=\"apollo\"}[1m])/rate(iot_apollo_api_get_timetables_seconds_count{job=\"apollo\"}[1m])"
    }
   ]
  },
  {
   "title": "HTTP 2xx /timetable",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"apollo\", uri=\"/timetables\", status=\"200\"}"
    }
   ]
  },
  {
   "title": "HTTP 5xx /timetable",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"apollo\", uri=\"/timetables\", status=\"500\"}"
    }
   ]
  },
  {
   "title": "Number of queries to Warsaw API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "GET Stops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "warsaw_api_get_stops_seconds_count{job=\"apollo\"}"
    }
   ]
  },
  {
   "title": "GET Vehicles on stop",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(warsaw_api_lines_on_stop_seconds_count{job=\"apollo\"}[1m])"
    }
   ]
  },
  {
   "title": "GET Timetables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "warsaw_api_timetables_seconds_count{job=\"apollo\"}"
    }
   ]
  },
  {
   "title": "GET Vehicles on stop AVG Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "rate(warsaw_api_lines_on_stop_seconds_sum{}[1m]) / rate(warsaw_api_lines_on_stop_seconds_count{}[1m])"
    }
   ]
  },
  {
   "title": "GET Timetable AVG Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "rate(warsaw_api_timetables_seconds_sum{}[1m]) / rate(warsaw_api_timetables_seconds_count{}[1m])"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Panel Title",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT line, lat, lon,\n       round(extract(epoch from timetable_departure_date - time) / 60) AS \"differences_in_seconds\",\n       $__time(time)\nFROM vehicle_timetable_delay\nWHERE is_on_stop = true AND abs(round(extract(epoch from time - timetable_departure_date) / 60)) >= 10;\n"
    }
   ]
  },
  { "title": "Panel Title", "type": "alertlist", "gridPos": { "h": 11, "w": 12, "x": 12, "y": 32 } }
 ]
}