### GET Buses
GET http://api.um.warszawa.pl/api/action/busestrams_get?apikey=a559863d-dea0-43aa-b994-361926f52ab0&resource_id=f2e5503e927d-4ad3-9500-4ab9e55deb59&type=1
Accept: application/json

### GET Trams
GET http://api.um.warszawa.pl/api/action/busestrams_get?apikey=a559863d-dea0-43aa-b994-361926f52ab0&resource_id=f2e5503e927d-4ad3-9500-4ab9e55deb59&type=2
Accept: application/json

### GET Stops
GET https://api.um.warszawa.pl/api/action/dbstore_get?apikey=a559863d-dea0-43aa-b994-361926f52ab0&id=ab75c33d-3a26-4342-b36a-6e5fef0a3ac3
Accept: application/json
