apiVersion: 1

datasources:
  - name: postgres
    type: postgres
    url: postgres:5432
    database: public_transport_db
    user: user
    secureJsonData:
      password: welcome1
    jsonData:
      sslmode: "disable"
  - name: iot_timetable_db
      type: iot_timetable_db
      url: iot_timetable_db:5432
      database: timetable_db
      user: user
      secureJsonData:
        password: welcome1
      jsonData:
        sslmode: "disable"
  - name: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: Y3oa11jMBJKnxTuXVNWXcpFZDryOb88F4re4LFMer3cucUixrBP0pl0W27ePhMG0hsKbHgkfVjs2VhLKJmh2ew==
    jsonData:
      version: Flux
      organization: public-transport
      defaultBucket: vehicles-bucket
      tlsSkipVerify: true
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false
