apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: Y3oa11jMBJKnxTuXVNWXcpFZDryOb88F4re4LFMer3cucUixrBP0pl0W27ePhMG0hsKbHgkfVjs2VhLKJmh2ew==
    jsonData:
      version: Flux
      organization: public-transport
      defaultBucket: vehicles-bucket
      tlsSkipVerify: true
