apiVersion: 1

datasources:
  - name: postgres
    type: postgres
    url: postgres:5432
    database: public_transport_db
    user: user
    secureJsonData:
      password: welcome1
    jsonData:
      sslmode: "disable"
