openapi: 3.0.0
info:
  title: Warsaw Public Transport API
  description: Warsaw Public Transport API
  version: 1.0.0
paths:
  /timetables:
    get:
      summary: Returns timetable for vehicle
      operationId: getTimetable
      parameters:
        - name: time
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: lat
          in: query
          required: true
          schema:
            type: number
            format: float
        - name: lon
          in: query
          required: true
          schema:
            type: number
            format: float
        - name: line
          in: query
          required: true
          schema:
            type: string
        - name: brigade
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Timetable'
  /stops/final-stops:
    get:
      summary: Return final stops for Warsaw
      operationId: getFinalStops
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinalStops'
components:
  schemas:
    Timetable:
      type: object
      properties:
        line:
          type: string
        brigade:
          type: string
        timetableDepartureDate:
          type: string
          format: date-time
        arrivalTime:
          type: string
          format: date-time
        vehicleDirection:
          type: string
        vahicleRoute:
          type: string
        is_on_stop:
          type: boolean
        has_timetable:
          type: boolean
        stopId:
          type: string
        stopNumber:
          type: string
        stopName:
          type: string
        stopLon:
          type: number
          format: float
        stopLat:
          type: number
          format: float
        stopDistance:
          description: Distace to closest stop in meters
          type: number
    Timetables:
      type: array
      items:
        $ref: '#/components/schemas/Timetable'
    FinalStop:
      type: object
      properties:
        line:
          type: string
        stopName:
          type: string
    FinalStops:
      type: array
      items:
        $ref: '#/components/schemas/FinalStop'

