openapi: 3.0.0
info:
  title: Warsaw Public Transport API
  description: Warsaw Public Transport API
  version: 1.0.0
servers:
  - url: 'https://api.um.warszawa.pl'
paths:
  /api/action/busestrams_get:
    get:
      summary: Returns list of Vehicles with theirs positions
      operationId: getVehicles
      parameters:
        - name: resource_id
          in: query
          required: true
          schema:
            type: string
        - name: apikey
          in: query
          required: true
          schema:
            type: string
        - name: type
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarsawVehicles'
components:
  schemas:
    WarsawVehicle:
      type: object
      properties:
        Lines:
          type: string
        Lat:
          type: string
        Lon:
          type: string
        VehicleNumber:
          type: string
        Brigade:
          type: string
        Time:
          type: string
    WarsawVehicles:
      type: object
      properties:
        result:
          type: array
          items:
            $ref: '#/components/schemas/WarsawVehicle'
