openapi: 3.0.0
info:
  title: Warsaw Public Transport API
  description: Warsaw Public Transport API
  version: 1.0.0
servers:
  - url: 'https://api.um.warszawa.pl'
paths:
  /api/action/busestrams_get:
    get:
      summary: Returns list of Vehicles with theirs positions
      operationId: getVehicles
      parameters:
        - name: resource_id
          in: query
          required: true
          schema:
            type: string
        - name: apikey
          in: query
          required: true
          schema:
            type: string
        - name: type
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarsawVehicles'
  /api/action/dbtimetable_get:
    get:
      summary: Return timetable for line on definied stop
      operationId: getTimetable
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
        - name: busstopId
          in: query
          required: true
          schema:
            type: string
        - name: busstopNr
          in: query
          required: true
          schema:
            type: string
        - name: line
          in: query
          required: true
          schema:
            type: string
        - name: apikey
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarsawTimetables'
  /api/action/dbstore_get:
    get:
      summary: Return the list of stops in Warsaw
      operationId: getStops
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
        - name: apikey
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarsawStops'
components:
  schemas:
    WarsawVehicle:
      type: object
      properties:
        Lines:
          type: string
        Lon:
          type: number
          format: float
        Lat:
          type: number
          format: float
        VehicleNumber:
          type: string
        Brigade:
          type: string
        Time:
          type: string
    WarsawVehicles:
      type: object
      properties:
        result:
          type: array
          items:
            $ref: '#/components/schemas/WarsawVehicle'
    WarsawTimetableValue:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    WarsawTimetable:
      type: object
      properties:
        values:
          type: array
          items:
            $ref: '#/components/schemas/WarsawTimetableValue'
    WarsawTimetables:
      type: object
      properties:
        result:
          type: array
          items:
            $ref: '#/components/schemas/WarsawTimetable'
    WarsawStopValue:
      type: object
      properties:
        value:
          type: string
        key:
          type: string
    WarsawStop:
      type: object
      properties:
        values:
          type: array
          items:
            $ref: '#/components/schemas/WarsawStopValue'
    WarsawStops:
      type: object
      properties:
        result:
          type: array
          items:
            $ref: '#/components/schemas/WarsawStop'
