{
 "title": "API",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Hermes",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"hermes\"}"
    }
   ]
  },
  {
   "title": "Apollo",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"apollo\"}"
    }
   ]
  },
  {
   "title": "GET Stops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(warsaw_api_get_stops_seconds_count{job=\"apollo\"}[1h])"
    }
   ]
  }
 ]
}