name: Build and Deploy to GKE

on:
  workflow_dispatch:
    inputs:
      artifact:
        type: choice
        description: Artifact id
        options:
          - iot-gps-collector
          - iot-timetable

jobs:
  setup-build-publish-deploy:
    name: Deploy GPS collector
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with maven
        run: cd ${{ inputs.artifact }} && mvn clean verify
