name: Build Artifact

on:
  workflow_dispatch:
    inputs:
      artifact:
        type: choice
        description: Artifact ID
        options:
          - iot-gtfs-collector
          - iot-gps-collector

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Artifact ${{ inputs.artifact }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - run: | 
          cd ${{ inputs.artifact }}
          pwd
          mvn clean verify
          mkdir staging
          cp  ${{ inputs.artifact }}/target/*.jar staging
