name: Deploy Snapshot Artifact

on:
  workflow_dispatch:
    inputs:
      artifact:
        type: choice
        description: Artifact ID
        options:
          - iot-gtfs-collector
          - iot-gps-collector

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          cache: 'maven'

      - name: Build with Maven
        run:  mvn package --file ${{ inputs.artifact }}/pom.xml -DskipTests

      - name: Read Snapshot version
        id: snapshot
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: ${{ inputs.artifact }}/target/maven-archiver/pom.properties
          properties: 'artifactId groupId version'

      - name: Print snapshot version
        run: echo ${{ steps.snapshot.outputs.version }}

      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: http://207.154.230.80/
          username: github
          password: ${{ secrets.password }}
          format: maven2
          repository: maven-releases
          coordinates: groupId=${{ inputs.groupId }} artifactId=${{ inputs.artifactId }} version=${{ inputs.version }}
          assets: extension=jar
          filename: ${{ inputs.artifact }}/target/*.jar
