name: Build Artifact

on:
  workflow_dispatch:
    inputs:
      artifact:
        type: choice
        description: Artifact id
        options:
          - iot-gps-collector
          - iot-timetable

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Artifact ${{ inputs.artifact }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - run: | 
          cd ${{ inputs.artifact }} 
          && mvn clean verify
      - run: mkdir staging && cp ${{ inputs.artifact }}/target/*.jar staging

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact }}
          path: staging
