name: Deploy Docker

on:
  workflow_dispatch:
    inputs:
      artifact:
        type: choice
        description: Artifact ID
        options:
          - iot-gtfs-server

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Artifact ${{ inputs.artifact }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - run: | 
          cd ${{ inputs.artifact }}
          pwd
          mvn clean verify
          mkdir staging
          cp  ${{ inputs.artifact }}/target/*.jar staging

      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v1.1.5
        with:
          app_name: ${{ inputs.artifact }}
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
