name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build maven project
        run: mvn clean compile

      - name: Build the Docker image
        run: docker build --file ./iot-timetable/Dockerfile --tag igeolab/iot-timetable-warsaw:$(date +%s) .
